---
- name: Debugging
  hosts: all
  connection: local

  tasks:
    - name: Print a message
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print another message
      ansible.builtin.debug:
        msg: "This is a test"
